version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      # Map our DB_* vars to Postgres’s expected ones
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"

  app:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      # Ensure the app connects to the "db" service
      - DB_HOST=db
      - DB_PORT=5432
      # DB_USER, DB_PASSWORD, DB_NAME, JWT_SECRET, etc., come from .env
      - PORT=${PORT:-3000}
      - NODE_ENV=development
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - db

volumes:
  db-data:
